Addwf21
jbosstools/jbosstools-server pull request #687
Opened 2020-09-23 07:03 UTC by robstryker

2020-09-23 08:11 UTC, jeffmaury commented
testPR

2020-09-24 14:08 UTC, jeffmaury requested changes
Also I noticed that there are some constants related to testing. You should contact QE as we decided to lower the number of runtimes QE is validating but I don't remember the rule

2020-09-24 14:08 UTC, jeffmaury commented on as/plugins/org.jboss.ide.eclipse.as.core/plugin.properties
> +jboss.version.wildfly20.name=WildFly 20
Wrong property keys, this is reported in the UI when creating a server.

2020-09-24 15:30 UTC, jeffmaury commented on as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/PomServerConstants.java
> +			JBOSS_190_HOME, JBOSS_200_HOME, JBOSS_210_HOME
That's the fist one to check with QE because I feel only the last 2 WF versions are listed here

2020-09-24 15:31 UTC, jeffmaury commented on as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerAdaptersTest.java
> +		list.add("WildFly 21");
Idem, I think only the 2 last WF versions should be listed here

2020-09-24 15:32 UTC, jeffmaury commented on as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
> +			WF_19_0_0, WF_20_0_0, WF_21_0_0};
Idem

2020-09-24 15:32 UTC, jeffmaury commented on as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
> +			WF_19_0_0, WF_20_0_0, WF_21_0_0}; //
Idem

2020-09-24 15:33 UTC, jeffmaury commented on as/itests/org.jboss.tools.as.ui.bot.itests/src/org/jboss/tools/as/ui/bot/itests/parametized/server/ServerRuntimeUIConstants.java
> +	public static final String[] SMOKETEST_DOWNLOADS = new String[] { JBEAP_730, WF_20_0_0, WF_21_0_0};
Seems only the latest from EAP and latest from WF should be listed here

2020-09-25 05:03 UTC, jkopriva commented
@jeffmaury you are right, we only test the latest 2 WF servers.

2020-09-25 21:22 UTC, merged

2020-09-25 21:22 UTC, robstryker commented
Merging even without that. Asking ondrej to remove the 3rd ones and to make sure it fits qe specs.

2020-09-25 21:22 UTC, robstryker commented
@odockal  please look into fixing how many runtimes are tested for?